
version: '3'
    
services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      #this is for local administration only
      ports:
        - "6543:5432"
    web:
      build: 
        dockerfile: Dockerfile
        context: ./img-baseclient
      #command: python manage.py runserver 0.0.0.0:8000
      command: >
        sh -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
      volumes:
        - ./img-baseclient:/code
      ports:
        - "8000:8000"
      depends_on:
        - db