version: '3'

networks:
  steelestack:

volumes:
  db-data:
    driver: local

services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      #this is for local administration only
      ports:
        - "6543:5432"
      #volumes:
        #- ./img-postgres/postgres-data:/var/lib/postgresql/data
      volumes:
        - db-data:/var/lib/postgresql/data
      networks:
        - steelestack
    web:
      build: 
        dockerfile: Dockerfile
        context: ./img-baseclient
      # command: >
      #   sh -c "pip install numpy &&
      #          pip freeze"
      # command: python manage.py runserver 0.0.0.0:8000
      command: >
        sh -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
      volumes:
        - ./img-baseclient:/code
      ports:
        - "8000:8000"
      networks:
        - steelestack
      depends_on:
        - db