# Generated by Django 2.2.15 on 2020-08-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_team', models.CharField(max_length=50)),
                ('go_live_date', models.DateField(verbose_name='go live date')),
            ],
        ),
    ]
