# Generated by Django 2.2.15 on 2020-08-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_engineer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_start_date', models.DateField(verbose_name='start date')),
                ('sprint_end_date', models.DateField(verbose_name='end date')),
            ],
        ),
    ]
