# Generated by Django 2.2.15 on 2020-08-20 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_pairing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engineer',
            options={'ordering': ['last_name']},
        ),
    ]
