# Generated by Django 2.2.15 on 2020-08-20 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20200820_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprintpairing',
            options={'verbose_name_plural': 'Sprint Assignments'},
        ),
        migrations.AlterField(
            model_name='sprint',
            name='project_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.ProjectTeam'),
        ),
        migrations.AlterField(
            model_name='sprintpairing',
            name='pairing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Pairing'),
        ),
    ]
