# Generated by Django 2.2.15 on 2020-08-23 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_auto_20200820_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pairing',
            name='member1',
        ),
        migrations.RemoveField(
            model_name='pairing',
            name='member2',
        ),
        migrations.RemoveField(
            model_name='sprintpairing',
            name='pairing',
        ),
        migrations.AddField(
            model_name='pairing',
            name='pair_member1',
            field=models.ForeignKey(default=1, limit_choices_to={'available_for_sprint': True}, on_delete=django.db.models.deletion.PROTECT, related_name='pair_member_a', to='schedule.Engineer', verbose_name='Team Member A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pairing',
            name='pair_member2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pair_member_b', to='schedule.Engineer', verbose_name='Team Member B'),
        ),
        migrations.AddField(
            model_name='sprintpairing',
            name='member1',
            field=models.ForeignKey(default=1, limit_choices_to={'available_for_sprint': True}, on_delete=django.db.models.deletion.PROTECT, related_name='team_member_a', to='schedule.Engineer', verbose_name='Team Member A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprintpairing',
            name='member2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team_member_b', to='schedule.Engineer', verbose_name='Team Member B'),
        ),
    ]
