# Generated by Django 2.2.15 on 2020-08-23 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20200823_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineer',
            name='avg_team_points_assigned',
        ),
        migrations.RemoveField(
            model_name='engineer',
            name='avg_team_points_completed',
        ),
    ]
